### ISSUE TITLE
Get building on travis

### ISSUE THREAD

**Issue by coreyhaines** [hamcrest/ramcrest#5]
Knowing that support is needed all the way back to 1.8.5, it would benefit the world if this was up and running on travis on as many rubies as possible! It is very straightforward to get running, as well as supporting a full test run on any pull requests. YAY!

**Comment by zaphod42** [comment]
It is up on travis :) I did that last night. 

http://travis-ci.org/zaphod42/ramcrest

**Comment by coreyhaines** [comment]
Cool. How about putting the build status into the Readme?

On Sun, Jul 1, 2012 at 12:41 PM, Andrew Parker <
reply@reply.github.com

**Comment by zaphod42** [comment]
Done!
